### ISSUE TITLE
What about Prometheus 2?

### ISSUE THREAD

**Issue by auhlig** [sapcc/maia#30]
For quite a while the Prometheans are working on Prometheus v2. It will introduce several breaking changes, such as a different storage model. Maia is currently hardcoded to the v1 API and does a HTTP GET to the relevant endpoint. This prevents us from upgrading the underlying Prometheus to v2.x . Making use of the remote read functionality would allow querying metrics without version constraints. This would require re-writing large parts of maia's storage layer. Worth a try IMO, as this approach avoids complexity and code duplication for for the v2 API. Makes sense?

**Comment by jobrs** [comment]
I checked their v2 API a few weeks ago and got the impression that it would not replace v1 but rather complement it with administrative operations. I would be interested in the remote TSDB interface though, so that the labels API call can be optimised.

Plans are to switch as soon as possible to benefit from the new storage engine.

https://github.com/prometheus/prometheus/blob/dev-2.0/documentation/dev/api/swagger.json
https://github.com/prometheus/prometheus/blob/dev-2.0/web/api/v2/api.go
https://groups.google.com/forum/#!topic/prometheus-developers/ZSqRV6SeVP8

I did not find any V2 API documentation so far. Only the above. Do you have a source?

**Comment by auhlig** [comment]
Maybe my 1st comment sounds to critical. I noticed the breaking changes introduced by the different storage models, so I wanted to point out that this could cause trouble for Maia and that remote read looks like a good way to avoid this. In addition utilizing remote read/write might be useful for long-term storage (crate.io). Best case would be just to exchange v1 with v2 in almost every http request maia does to communicate with prometheus. But then maia would be fixed to one prometheus version. I haven't looked further into this. The v2 API is currently only "documented" in the code you linked above, I think.
 
I thought it's worth opening an issue on this topic since Prometheus 1.8 appears to be the last 1.x release.

**Comment by jobrs** [comment]
Having the issue makes sense, I just wanted to have the 2.0 API first. Let's keep it open until we have a list of addressable work packages (i.e. other issues). 

Are your sure that v2 replaces v1? I think the existing v1 operations stay in v1 except for DELETE /series. Regarding v2 extensions I am not sure whether we need to expose these at all.

Long-term storage: I do not have the full picture how long-term storage would look like from customer perspective. My current understanding is that the remove read/write API is intended to write storage drivers, so that Prometheus can write and read-back data outside its own retention window. Or is this even pluggable storage? Anyway, I believe the customer facing API will not change and that should not affect the Maia codebase but rather the Prometheus instances behind.

**Comment by jobrs** [comment]
Prometheus has been upgraded to 2.5 meanwhile
